<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
</head>
<body>
	<h1>Contact me</h1>
	<p>Profile</p>
	<form action="contact/submit" method="post">
		<input type="input" name="Username"><br>
		<input type="input" name="Birth"><br>
		<input type="input" name="Biography"><br>
		<input type="input" name="Interests"><br>
		<button type="submit">Submit</button>
	</form>

	<p><a href="/home">Home</a></p>
</body>
</html>